export default {
  links: [
    {
      status: "active",
      score: 1,
      uri: "http://adit.io/posts/2013-04-17-functors,_applicatives,_and_monads_in_pictures.html",
      owner: 1,
      source: "pinboard",
      id: "pinboard:cbf7274312d920d2446209b8cdbe7e1e",
      title: "Functors, Applicatives, And Monads In Pictures",
    },
    {
      status: "active",
      score: 1,
      uri: "https://blog.feabhas.com/2021/06/why-we-need-build-systems/",
      owner: 1,
      source: "pinboard",
      id: "pinboard:1bbada44af978dc109efdfee471d9e74",
      title: "Why we need build systems",
    },
    {
      status: "active",
      score: 1,
      uri: "https://hacks.mozilla.org/2017/02/a-crash-course-in-just-in-time-jit-compilers/",
      owner: 1,
      source: "pinboard",
      id: "pinboard:4acc80f19722310f6ec67e3b3d2d7b8c",
      title: "Crash course in JIT",
    },
    {
      status: "active",
      score: 1,
      uri: "https://www.youtube.com/watch?v=0wqUWYx3UrY",
      owner: 1,
      source: "pinboard",
      id: "pinboard:6224f3bef30ee1fc00a9461339fd074e",
      title: "How To Make A $300 Camera Look Pro",
    },
    {
      status: "active",
      score: 1,
      uri: "https://lemire.me/blog/2019/01/30/what-is-the-space-overhead-of-base64-encoding/",
      owner: 1,
      source: "pinboard",
      id: "pinboard:9acdbb2b14ef6b1f5dc351aa5e261719",
      title: "What is the space overhead of Base64 encoding?",
    },
  ],
};
